In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv('titanic.csv')

In [4]:
#finding the name of the columns
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [8]:
#shape of the dataframe
df.shape
print(f"The number of rows are :{df.shape[0]}")
print(f"The number of columns are :{df.shape[1]}")

The number of rows are :891
The number of columns are :9

In [9]:
#statistical description.

df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [10]:
#first few rows of the dataframe
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [11]:
#last 5 rows of the dataframe
df.tail()

     survived  pclass  gender   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [13]:
#checking the number of nan values in each column
df.isna().sum()

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [18]:
#checking the unique value in the embarked column
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [19]:
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [20]:
#age between 20 and 2
df[(df['age'] > 2) & (df['age'] < 20)]

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
9           1       2  female  14.0      1      0  30.0708        C  NaN
10          1       3  female   4.0      1      1  16.7000        S    G
14          0       3  female  14.0      0      0   7.8542        S  NaN
22          1       3  female  15.0      0      0   8.0292        Q  NaN
24          0       3  female   8.0      3      1  21.0750        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
855         1       3  female  18.0      0      1   9.3500        S  NaN
869         1       3    male   4.0      1      1  11.1333        S  NaN
875         1       3  female  15.0      0      0   7.2250        C  NaN
877         0       3    male  19.0      0      0   7.8958        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B

[140 rows x 9 columns]

In [21]:
df[(df['gender'] == 'female') & (df['pclass'] == 1)]

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
1           1       1  female  38.0      1      0   71.2833        C    C
3           1       1  female  35.0      1      0   53.1000        S    C
11          1       1  female  58.0      0      0   26.5500        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
52          1       1  female  49.0      1      0   76.7292        C    D
..        ...     ...     ...   ...    ...    ...       ...      ...  ...
856         1       1  female  45.0      1      1  164.8667        S  NaN
862         1       1  female  48.0      0      0   25.9292        S    D
871         1       1  female  47.0      1      1   52.5542        S    D
879         1       1  female  56.0      0      1   83.1583        C    C
887         1       1  female  19.0      0      0   30.0000        S    B

[94 rows x 9 columns]

In [23]:
#average age of the male and the female passanger
df.groupby('gender')['age'].mean()

gender
female    27.915709
male      30.726645
Name: age, dtype: float64

In [24]:
#no of passanger in each passanger class
df['pclass'].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [25]:
df_survived=df[df['survived']==1]
df_not_survived=df[df['survived']==0]

In [26]:
df_survived['gender'].value_counts()

gender
female    233
male      109
Name: count, dtype: int64

In [27]:
df_not_survived['gender'].value_counts()

gender
male      468
female     81
Name: count, dtype: int64

In [29]:
df['age'].dtype

dtype('float64')

In [30]:
df.sort_values(by='age', ascending=False).head(3)

     survived  pclass gender   age  sibsp  parch     fare embarked deck
630         1       1   male  80.0      0      0  30.0000        S    A
851         0       3   male  74.0      0      0   7.7750        S  NaN
493         0       1   male  71.0      0      0  49.5042        C  NaN